export const SET_RESPONSE = "ADD_RESPONSE";
export type SET_RESPONSE = typeof SET_RESPONSE;

export const SET_LOADING_KEYSTATS = "SET_LOADING_KEYSTATS";
export type SET_LOADING_KEYSTATS = typeof SET_LOADING_KEYSTATS;

export const SET_ERROR_KEYSTATS = "SET_ERROR_KEYSTATS";
export type SET_ERROR_KEYSTATS = typeof SET_ERROR_KEYSTATS;
