export const ADD_COMPANY_OVERVIEW = "ADD_COMPANY_OVERVIEW";
export type ADD_COMPANY_OVERVIEW = typeof ADD_COMPANY_OVERVIEW;

export const SET_LOADING_OVERVIEW = "SET_LOADING_OVERVIEW";
export type SET_LOADING_OVERVIEW = typeof SET_LOADING_OVERVIEW;

export const SET_ERROR_OVERVIEW = "SET_ERROR_OVERVIEW";
export type SET_ERROR_OVERVIEW = typeof SET_ERROR_OVERVIEW;
